### ISSUE TITLE
every time I run the app from pinned icon on taskbar while it is running on system tray, it is checking for updates and giving me notification which is quite redundant and annoying

### ISSUE THREAD

**Issue by mdyamin007** [anwar3606/google-chat-webapp#12]
every time I run the app from pinned icon on taskbar while it is running on system tray, it is checking for updates and giving me notification. I think it is quite redundant and annoying.

**Comment by anwar3606** [comment]
remove those notification, they aren't necessary, only keep the one to notify users that there is a new version available and it will be automatically updated to the latest one
